/* Toro course content.
 *
 * Each course has units, each unit has lessons, each lesson has a short tip and five questions.
 * Authoring rule: for MC and FILL, the FIRST option is the correct one. The app shuffles options.
 * ORDER lists items in the correct order. MATCH lists [term, meaning] pairs.
 * `apply` (optional) links a lesson to a place in the app to practice it, e.g. '#AAPL' or '#tools'.
 */
(function(){
const MC    = (q, o, why) => ({t:'mc', q, o, why});
const TF    = (q, a, why) => ({t:'tf', q, a, why});
const FILL  = (q, o, why) => ({t:'fill', q, o, why});
const MATCH = (pairs, why) => ({t:'match', q:'Match each term to its meaning', pairs, why});
const ORDER = (q, items, why) => ({t:'order', q, items, why});
const L = (t, tip, qs, apply) => ({t, tip, qs, apply});

window.TORO_COURSES = [
{
  id:'invest', name:'Stocks & Investing', color:'#2BB673',
  blurb:'What stocks are, why prices move, and how to build a portfolio that lasts.',
  units:[
    {t:'Owning a piece of a company', lessons:[
      L('What is a stock?',
        'A stock, or share, is a small slice of ownership in a company. If you own shares you are a shareholder: you share in the company’s profits and its losses. Each stock has a short code called a ticker, like AAPL for Apple.',
        [ MC('What do you own when you buy a share of stock?', ['A small piece of the company','A loan to the company','A coupon for its products'], 'A share is partial ownership. Lending money to a company is a bond.'),
          TF('A ticker is the short code used to identify a stock, like AAPL for Apple.', true, 'Tickers make stocks quick to look up and trade.'),
          FILL('People who own shares in a company are called ___.', ['shareholders','lenders','customers'], 'Shareholders are part-owners of the company.'),
          MATCH([['Stock','A slice of ownership'],['Ticker','Short code for a stock'],['Exchange','Marketplace where shares trade'],['Shareholder','Person who owns shares']]),
          MC('Where are shares of public companies bought and sold?', ['On a stock exchange','Only at company headquarters','At a bank vault'], 'Exchanges match buyers and sellers.') ], '#AAPL'),
      L('Why prices move',
        'Buyers and sellers set a stock’s price. When more people want to buy than sell, the price rises. When more want to sell, it falls. Market capitalization is the total value of all the shares: price × number of shares.',
        [ MC('If far more people want to buy a stock than sell it, the price usually…', ['Rises','Falls','Stays the same'], 'Demand greater than supply pushes prices up.'),
          MC('A company has 10 million shares at $50 each. What is its market cap?', ['$500 million','$50 million','$5 billion'], '10,000,000 × $50 = $500,000,000.'),
          TF('A higher share price always means a bigger company.', false, 'Size is market cap. A $500 stock with few shares can be smaller than a $20 stock with billions of shares.'),
          FILL('Market cap = share price × number of ___.', ['shares','employees','customers'], 'Multiply price by shares outstanding.'),
          MC('Which news would most likely push a stock DOWN?', ['The company cuts its profit forecast','The company beats earnings expectations','The company wins a big contract'], 'Lower expected profits make shares less attractive.') ]),
      L('How investors get paid',
        'Investors make money in two ways. A capital gain is selling for more than you paid. A dividend is cash some companies pay out of their profits. Dividend yield = yearly dividend ÷ share price.',
        [ MATCH([['Capital gain','Profit from selling higher'],['Dividend','Cash paid out of profits'],['Dividend yield','Yearly dividend as % of price'],['Capital loss','Selling for less than you paid']]),
          MC('You buy at $40 and sell at $50. Your capital gain per share is…', ['$10','$50','$90'], '$50 − $40 = $10.'),
          MC('A stock costs $100 and pays $3 a year in dividends. What is the yield?', ['3%','30%','0.3%'], '$3 ÷ $100 = 3%.'),
          TF('Every company pays a dividend.', false, 'Many growing companies reinvest their profits instead of paying dividends.'),
          FILL('Selling a stock for more than you paid creates a capital ___.', ['gain','loss','tax'], 'Sell high, buy low: that difference is the gain.') ], '#KO'),
    ]},
    {t:'Building a portfolio', lessons:[
      L('Don’t put all your eggs in one basket',
        'Diversification means spreading money across many companies and sectors. If one company has a bad year, the others soften the blow. It lowers risk without needing to predict winners.',
        [ MC('Which portfolio is most diversified?', ['20 stocks across 7 sectors','5 technology stocks','1 stock you really like'], 'More companies across more sectors spreads risk.'),
          TF('Diversification removes all risk.', false, 'It lowers company-specific risk, but the whole market can still fall.'),
          FILL('Spreading money across many investments is called ___.', ['diversification','leverage','speculation'], 'Diversify to reduce the damage from any one loser.'),
          MC('Why hold stocks from different sectors?', ['Sectors often react differently to the same news','It guarantees higher returns','It avoids all taxes'], 'High oil prices can hurt airlines but help energy producers.'),
          MC('80% of your portfolio is one stock. What is the main risk?', ['One bad result could hurt most of your money','You will pay too many fees','Your dividends will be too high'], 'Concentration ties your fate to one company.') ], '#portfolio'),
      L('Index funds and ETFs',
        'An index fund buys every company in an index. SPY, for example, tracks the S&P 500. An ETF (exchange-traded fund) is a fund that trades like a stock. The expense ratio is the yearly fee, as a percentage of what you invest.',
        [ MATCH([['Index fund','Owns every stock in an index'],['ETF','Fund that trades like a stock'],['Expense ratio','Yearly fund fee as a %'],['Index','A list tracking a group of stocks']]),
          MC('You invest $10,000 in a fund with a 0.10% expense ratio. The yearly fee is about…', ['$10','$100','$1,000'], '0.10% of $10,000 = $10.'),
          TF('An index fund tries to match the market, not beat it.', true, 'That is why index funds are called passive investing.'),
          MC('What is a big advantage of an index fund for beginners?', ['Instant diversification at low cost','Guaranteed profits','No price swings'], 'One purchase spreads your money across the market.'),
          FILL('A fund that trades on an exchange like a stock is an ___.', ['ETF','IPO','APR'], 'ETF = exchange-traded fund.') ], '#SPY'),
      L('Time and compounding',
        'Compounding means your gains start earning gains of their own. The longer you stay invested, the bigger the effect. Money you need soon should take less risk than money you won’t touch for 20 years.',
        [ MC('$1,000 grows 10% a year. After 2 years it is worth…', ['$1,210','$1,200','$1,100'], 'Year 1: $1,100. Year 2: $1,100 × 1.10 = $1,210. The extra $10 is compounding.'),
          TF('Money you need next month is usually better kept out of stocks.', true, 'Stocks can drop sharply over short periods.'),
          ORDER('Order from lowest to highest typical risk', ['Savings account','Bond fund','Index fund','Single small biotech stock'], 'Fewer, riskier holdings mean bigger swings.'),
          FILL('Earning returns on your past returns is called ___.', ['compounding','hedging','shorting'], 'Growth on growth.'),
          MC('Rule of 72: at 8% a year, money doubles in about…', ['9 years','72 years','8 years'], '72 ÷ 8 = 9.') ], '#tools'),
    ]},
  ]
},
{
  id:'trading', name:'Trading', color:'#4C8DF0',
  blurb:'Order types, reading charts, and the risk rules traders live by.',
  units:[
    {t:'Placing orders', lessons:[
      L('Market and limit orders',
        'A market order fills right away at the best available price. A limit order sets your price: a buy limit fills at your price or lower, a sell limit at your price or higher. A limit order might never fill.',
        [ MC('You want to buy right now, whatever the price. Use a…', ['Market order','Limit order','Stop order'], 'Market orders trade immediately.'),
          MC('A stock is at $142. You place a buy limit at $135. When does it fill?', ['When the price falls to $135 or lower','Right away at $142','Never, limit orders can’t buy'], 'A buy limit waits for your price or better.'),
          TF('A limit order guarantees your trade will happen.', false, 'It guarantees the price, not the fill.'),
          FILL('A sell limit fills at your price or ___.', ['higher','lower','never'], 'Sellers want the same or better, which means higher.'),
          MATCH([['Market order','Fills now at current price'],['Buy limit','Fills at your price or lower'],['Sell limit','Fills at your price or higher'],['Fill','When an order executes']]) ], '#AAPL'),
      L('Stop orders',
        'A stop-loss order sells automatically if the price falls to a level you set, capping your loss. When the stop price is hit it becomes a market order. A stop-limit becomes a limit order instead: it controls the price but might not fill.',
        [ MC('You bought at $50 and want to cap your loss near 10%. Where is your stop?', ['$45','$55','$40'], '10% below $50 is $45.'),
          TF('When a stop-loss triggers, it becomes a market order.', true, 'That is why it can fill below your stop in a fast drop.'),
          MC('What is the risk of a stop-limit order in a fast drop?', ['It may not fill at all','It sells at a huge premium','It buys more shares'], 'If the price gaps below your limit, nothing sells.'),
          FILL('An order that sells automatically to cap losses is a ___.', ['stop-loss','limit buy','margin call'], 'Set it when you enter the trade.'),
          MC('Why do traders use stop-losses?', ['To decide their exit before emotions kick in','To guarantee profits','To avoid paying the spread'], 'Planning the exit in advance keeps decisions calm.') ]),
      L('Spread and liquidity',
        'The bid is the highest price buyers will pay. The ask is the lowest price sellers will accept. The gap is the spread. Liquid stocks trade a lot and have tight spreads. Slippage is getting a worse price than you expected.',
        [ MATCH([['Bid','Highest price a buyer offers'],['Ask','Lowest price a seller accepts'],['Spread','Gap between bid and ask'],['Slippage','Filling at a worse price']]),
          MC('Bid $19.95, ask $20.05. The spread is…', ['$0.10','$0.05','$20.00'], '$20.05 − $19.95 = $0.10.'),
          TF('Stocks that trade in huge volumes usually have wider spreads.', false, 'Heavy trading usually means tight spreads.'),
          MC('A market buy order usually fills at the…', ['Ask','Bid','Last close'], 'Buyers pay the sellers’ asking price.'),
          FILL('A stock that is easy to buy and sell quickly is highly ___.', ['liquid','volatile','leveraged'], 'Liquidity is ease of trading without moving the price.') ]),
    ]},
    {t:'Charts and risk', lessons:[
      L('Reading candlesticks',
        'Each candlestick shows one period’s open, high, low and close (OHLC). The body runs from open to close. Green means it closed higher than it opened, red means lower. The thin wicks mark the high and low.',
        [ MATCH([['Open','First price of the period'],['Close','Last price of the period'],['High','Top of the upper wick'],['Low','Bottom of the lower wick']]),
          TF('A green candle means the close was above the open.', true, 'Green = up for the period.'),
          MC('A candle with a tiny body and long wicks suggests…', ['Buyers and sellers fought to a draw','A huge one-way rally','The market was closed'], 'Price moved a lot but ended near where it started.'),
          FILL('OHLC stands for open, high, low and ___.', ['close','cost','cap'], 'The four prices in every candle.'),
          MC('The thin lines above and below a candle’s body are called…', ['Wicks','Spreads','Tickers'], 'Also called shadows.') ]),
      L('Trends and levels',
        'An uptrend makes higher highs and higher lows. Support is a price where buying has tended to stop declines. Resistance is where selling has capped rallies. A moving average smooths prices to show the trend.',
        [ MC('Higher highs and higher lows describe…', ['An uptrend','A downtrend','A sideways market'], 'Each rally and dip ends higher than the last.'),
          MATCH([['Support','Where declines have stopped'],['Resistance','Where rallies have stalled'],['Moving average','Average over a rolling window'],['Breakout','Price moves past resistance']]),
          TF('Support and resistance levels are guaranteed to hold.', false, 'They are zones where things happened before, not rules.'),
          MC('A 50-day moving average is…', ['The average close of the last 50 days','The price 50 days ago','The highest price in 50 days'], 'It rolls forward each day.'),
          FILL('When price pushes above resistance, it is called a ___.', ['breakout','dividend','split'], 'Breakouts often come with higher volume.') ]),
      L('Managing risk',
        'Professionals decide how much they could lose before they trade. A common rule: risk no more than 1–2% of your account on one trade. Risk/reward compares what you could lose with what you could gain.',
        [ MC('Account: $10,000. Using the 1% rule, the most you would risk on one trade is…', ['$100','$1,000','$10'], '1% of $10,000 = $100.'),
          MC('Stop $2 below entry, target $6 above. The risk/reward is…', ['1:3','3:1','1:6'], 'Risk $2 to make $6.'),
          TF('Doubling your position after a loss to “win it back” is sound risk management.', false, 'That is revenge trading, and it grows losses.'),
          ORDER('Put a disciplined trade in order', ['Pick a setup','Set your stop and target','Size the position','Place the order','Review the result'], 'You need the stop before you can size the trade.'),
          FILL('Choosing how many shares to buy based on your risk is position ___.', ['sizing','trading','margin'], 'Size = amount at risk ÷ distance to stop.') ], '#portfolio'),
    ]},
  ]
},
{
  id:'money', name:'Personal Finance', color:'#E0A43A',
  blurb:'Budgeting, emergency funds, credit scores and getting out of debt.',
  units:[
    {t:'Budgeting basics', lessons:[
      L('Where your money goes',
        'A budget is a plan for your income. The 50/30/20 rule is a simple start: 50% to needs, 30% to wants, 20% to savings and paying off debt, all from take-home pay.',
        [ MC('Take-home pay is $3,000 a month. Under 50/30/20, savings get…', ['$600','$900','$1,500'], '20% of $3,000 = $600.'),
          MATCH([['Needs','Rent, groceries, utilities'],['Wants','Streaming, dining out, concerts'],['Savings','Emergency fund, investing'],['Take-home pay','Income after taxes']]),
          TF('A gym membership you rarely use is a need.', false, 'Unused subscriptions are wants, and easy cuts.'),
          FILL('Under 50/30/20, ___% of take-home pay goes to needs.', ['50','30','20'], 'Needs get half.'),
          MC('The first step in making a budget is…', ['Tracking what you actually spend','Cutting all fun spending','Opening a credit card'], 'You can’t plan what you haven’t measured.') ]),
      L('Emergency fund',
        'An emergency fund covers surprises like a job loss or a car repair. Aim for 3–6 months of essential expenses in a safe, easy-to-reach account such as a high-yield savings account.',
        [ MC('Essential costs are $2,000 a month. A 3–6 month emergency fund is…', ['$6,000–$12,000','$2,000','$24,000–$48,000'], '3 × $2,000 to 6 × $2,000.'),
          TF('Emergency funds are best kept in individual stocks.', false, 'Stocks can fall right when you need the cash.'),
          MC('Which is a true emergency?', ['A surprise medical bill','A concert ticket sale','A new phone release'], 'Emergencies are unplanned and necessary.'),
          FILL('Emergency money should be safe and easy to ___.', ['access','forget','invest'], 'You may need it tomorrow.'),
          MC('Why build an emergency fund before investing heavily?', ['So you don’t sell investments at a bad time','Savings always earn more than stocks','Investing is illegal without one'], 'Cash on hand keeps your investments untouched.') ]),
      L('Pay yourself first',
        'Paying yourself first means moving savings out automatically on payday, before you spend. Small automatic amounts add up, and money you never see is money you don’t miss.',
        [ TF('Automating savings on payday makes saving easier.', true, 'It removes the decision each month.'),
          MC('Saving $5 a day for a year adds up to about…', ['$1,825','$365','$500'], '$5 × 365 = $1,825.'),
          ORDER('Order a simple money plan', ['Build a starter emergency fund','Pay off high-interest debt','Grow the fund to 3–6 months','Invest for the long term'], 'Protect yourself, kill expensive debt, then grow.'),
          FILL('Saving before you spend is called paying yourself ___.', ['first','last','back'], 'Savings come out before spending.'),
          MC('Lifestyle creep means…', ['Spending rises as income rises','Prices fall over time','Saving becomes automatic'], 'Raises vanish into new spending.') ], '#tools'),
    ]},
    {t:'Credit and debt', lessons:[
      L('Interest and APR',
        'Interest is the cost of borrowing. APR (annual percentage rate) shows the yearly cost, including many fees. Credit card APRs are often above 20%, so unpaid balances grow quickly.',
        [ MC('A $1,000 card balance at 24% APR sits unpaid for a year. Interest is roughly…', ['$240','$24','$2,400'], '24% of $1,000 ≈ $240, and more once interest compounds.'),
          TF('Paying only the minimum is the cheapest way to clear a credit card.', false, 'Minimums keep most of the balance growing at full APR.'),
          FILL('The yearly cost of borrowing, shown as a percentage, is the ___.', ['APR','ETF','IPO'], 'Annual percentage rate.'),
          MATCH([['Principal','Amount you borrowed'],['Interest','Cost of borrowing'],['APR','Yearly cost as a %'],['Minimum payment','Smallest amount due monthly']]),
          MC('Which usually has the highest interest rate?', ['Credit card','Mortgage','Federal student loan'], 'Unsecured card debt is the priciest.') ]),
      L('Credit scores',
        'A credit score estimates how likely you are to repay. The biggest factors are paying on time and how much of your credit limit you use, called utilization. Keeping utilization under about 30% helps.',
        [ MC('Which matters most for a credit score?', ['Paying bills on time','Your salary','How many bank accounts you have'], 'Payment history is the largest factor.'),
          MC('Limit $5,000, balance $1,000. Utilization is…', ['20%','5%','50%'], '$1,000 ÷ $5,000 = 20%.'),
          TF('Checking your own credit score lowers it.', false, 'Checking your own score is a soft inquiry.'),
          FILL('Using a small share of your credit limit keeps ___ low.', ['utilization','income','APR'], 'Lower utilization looks less risky.'),
          MC('A good credit score can get you…', ['Lower interest rates on loans','Free stocks','Higher taxes'], 'Lenders charge less to reliable borrowers.') ]),
      L('Paying off debt',
        'There are two popular payoff methods. Avalanche: pay extra on the highest-interest debt first, which saves the most money. Snowball: pay off the smallest balance first, for quick wins that keep you going. Either way, pay the minimum on everything.',
        [ MATCH([['Avalanche','Highest interest rate first'],['Snowball','Smallest balance first'],['Minimum payment','Pay on every debt monthly'],['Refinancing','Swap a loan for a cheaper one']]),
          MC('Which method saves the most interest?', ['Avalanche','Snowball','Paying at random'], 'Killing the highest rate first cuts total interest.'),
          TF('With the snowball method you stop paying minimums on bigger debts.', false, 'Always pay every minimum to avoid fees and credit damage.'),
          MC('Debts: card 25% APR, car 6%, student 4%. Avalanche targets first…', ['The card','The car loan','The student loan'], 'Highest rate first.'),
          FILL('Paying the smallest balance first is the debt ___ method.', ['snowball','avalanche','ladder'], 'Small wins build momentum.') ]),
    ]},
  ]
},
{
  id:'biz', name:'Marketing & Business', color:'#E0567F',
  blurb:'Finding customers, standing out, and the numbers that run a business.',
  units:[
    {t:'Marketing basics', lessons:[
      L('The 4 Ps',
        'The marketing mix is often called the 4 Ps: Product (what you sell), Price (what it costs), Place (where people buy it) and Promotion (how people hear about it).',
        [ MATCH([['Product','What you sell'],['Price','What customers pay'],['Place','Where customers buy it'],['Promotion','How customers hear about it']]),
          MC('A brand runs Instagram ads. Which P is that?', ['Promotion','Place','Product'], 'Ads spread the word.'),
          MC('Selling in grocery stores instead of only online changes the…', ['Place','Price','Product'], 'Place is where the sale happens.'),
          TF('Offering a student discount is a Price decision.', true, 'Discounts change what customers pay.'),
          FILL('The 4 Ps are product, price, place and ___.', ['promotion','profit','people'], 'Promotion completes the mix.') ]),
      L('Knowing your customer',
        'Segmentation splits a market into groups with shared needs, by age, location, behavior or values. Your target market is the segment you choose to serve. A persona is a sketch of one typical customer.',
        [ MC('Selling running shoes to marathon runners is choosing a…', ['Target market','Supply chain','Price floor'], 'You picked a segment to serve.'),
          MATCH([['Segmentation','Splitting a market into groups'],['Target market','The group you choose to serve'],['Persona','Profile of a typical customer'],['Demographics','Age, income, location']]),
          TF('Marketing to everyone usually works better than choosing a target.', false, 'A message for everyone speaks to no one.'),
          FILL('Grouping customers by shared traits is called ___.', ['segmentation','distribution','inflation'], 'Segments make messages sharper.'),
          MC('Which is a behavioral segment?', ['People who buy coffee daily','People aged 25–34','People in Chicago'], 'Behavior is what people do, not who or where they are.') ]),
      L('Standing out',
        'A value proposition says why a customer should pick you: the problem you solve and what makes you different. Positioning is the place you want to hold in customers’ minds compared with competitors.',
        [ MC('Which is the strongest value proposition?', ['Groceries at your door in 15 minutes','We are a great company','Quality products for everyone'], 'Specific, customer-focused and different.'),
          TF('Positioning is about how customers see you compared with competitors.', true, 'It is relative by nature.'),
          FILL('The promise of why customers should choose you is your value ___.', ['proposition','chain','ratio'], 'Value proposition.'),
          MC('A brand known as “the safest car” in people’s minds has strong…', ['Positioning','Liquidity','Leverage'], 'It owns one clear idea.'),
          ORDER('Order a basic marketing plan', ['Research the market','Choose a target segment','Write the value proposition','Launch promotion','Measure results'], 'Know who, say why, then spread the word and measure.') ]),
    ]},
    {t:'Business by the numbers', lessons:[
      L('Revenue, profit and margin',
        'Revenue is money from sales. Profit is what is left after costs. Profit margin = profit ÷ revenue. A 20% margin means 20 cents of profit on every dollar of sales.',
        [ MC('Revenue $200,000, costs $150,000. Profit is…', ['$50,000','$350,000','$150,000'], '$200,000 − $150,000.'),
          MC('Profit $50,000 on revenue $200,000. The margin is…', ['25%','50%','4%'], '$50,000 ÷ $200,000 = 25%.'),
          TF('A company with high revenue is always profitable.', false, 'Costs can exceed revenue.'),
          MATCH([['Revenue','Money in from sales'],['Costs','Money spent running the business'],['Profit','Revenue minus costs'],['Margin','Profit as a % of revenue']]),
          FILL('Profit divided by revenue is profit ___.', ['margin','volume','yield'], 'Profit margin.') ]),
      L('Customer economics',
        'CAC (customer acquisition cost) is what you spend to win one customer. LTV (lifetime value) is the profit a customer brings over time. Healthy businesses aim for LTV of about 3× CAC or more.',
        [ MC('$10,000 on ads brings 200 customers. CAC is…', ['$50','$200','$2,000'], '$10,000 ÷ 200.'),
          TF('If LTV is lower than CAC, you lose money on each customer.', true, 'You pay more to win them than they bring in.'),
          MATCH([['CAC','Cost to win one customer'],['LTV','Profit from a customer over time'],['Churn','Customers who leave'],['Retention','Customers who stay']]),
          MC('Which improves LTV?', ['Customers stay subscribed longer','Spending more on ads','Raising CAC'], 'Longer relationships mean more profit per customer.'),
          FILL('The share of customers who cancel is called ___.', ['churn','margin','reach'], 'Lower churn, higher LTV.') ]),
      L('The sales funnel',
        'A funnel tracks people from first hearing about you to buying: awareness, interest, decision, action. Conversion rate = buyers ÷ visitors. Small improvements at each step multiply.',
        [ ORDER('Put the funnel stages in order', ['Awareness','Interest','Decision','Action'], 'AIDA, from first contact to purchase.'),
          MC('1,000 visitors and 30 buy. The conversion rate is…', ['3%','30%','0.3%'], '30 ÷ 1,000.'),
          TF('Doubling your conversion rate can double sales without more traffic.', true, 'Same visitors, twice the buyers.'),
          FILL('Buyers divided by visitors is the ___ rate.', ['conversion','churn','interest'], 'Conversion rate.'),
          MC('Many people add to cart but don’t buy. Which stage leaks?', ['Action (checkout)','Awareness','Interest'], 'They decided but didn’t complete the purchase.') ]),
    ]},
  ]
},
{
  id:'supply', name:'Global Supply Chains', color:'#22B8C8',
  blurb:'How goods cross the world, who pays for shipping, and how companies handle shocks.',
  units:[
    {t:'How goods get to you', lessons:[
      L('The chain',
        'A supply chain is every step that turns raw materials into a product in your hands: suppliers, manufacturers, distributors, retailers and customers. A phone can pass through a dozen countries before you buy it.',
        [ ORDER('Put the supply chain in order', ['Raw materials','Manufacturer','Distributor','Retailer','Customer'], 'Materials become products that flow toward buyers.'),
          MC('A company that makes finished goods from parts is a…', ['Manufacturer','Retailer','Distributor'], 'Manufacturers transform inputs.'),
          TF('Most complex products rely on suppliers in more than one country.', true, 'Chips, screens and batteries often come from different places.'),
          MATCH([['Supplier','Provides raw materials or parts'],['Manufacturer','Turns inputs into products'],['Distributor','Moves and stores goods in bulk'],['Retailer','Sells to end customers']]),
          FILL('The network that brings a product from raw materials to you is the supply ___.', ['chain','curve','line'], 'Supply chain.') ]),
      L('Moving freight',
        'Most world trade by volume moves by sea in standard containers, counted in TEU (twenty-foot equivalent units). Air is fastest but most expensive. Rail and trucks connect ports to warehouses.',
        [ MC('Which mode carries most world trade by volume?', ['Ocean shipping','Air freight','Trucks'], 'Roughly 80% of goods by volume travel by sea.'),
          MC('A 40-foot container equals how many TEU?', ['2','1','4'], 'TEU = twenty-foot equivalent, so 40 ft = 2.'),
          TF('Air freight is usually the cheapest way to ship heavy goods.', false, 'Air costs many times more per kilogram than ocean.'),
          MATCH([['Ocean','Cheapest per unit in bulk'],['Air','Fastest and most expensive'],['Rail','Long overland bulk hauls'],['Truck','Door-to-door last leg']]),
          FILL('Container capacity is measured in ___.', ['TEU','APR','ETF'], 'Twenty-foot equivalent units.') ], '#FDX'),
      L('Who pays for what: Incoterms',
        'Incoterms are standard trade terms that say who pays for shipping and who carries the risk. EXW: the buyer handles almost everything from the seller’s door. FOB: risk passes once goods are loaded on the ship. DDP: the seller delivers to the buyer with duties paid.',
        [ MATCH([['EXW','Buyer collects at seller’s site'],['FOB','Risk passes when loaded on ship'],['DDP','Seller delivers, duties paid'],['CIF','Seller pays cost, insurance, freight']]),
          MC('Which term puts the most work on the seller?', ['DDP','EXW','FOB'], 'Delivered Duty Paid: the seller handles it all.'),
          TF('Under FOB, risk passes to the buyer once the goods are loaded on the ship.', true, 'Free On Board.'),
          MC('Incoterms mainly define…', ['Who pays costs and bears risk at each step','Product prices','Import tax rates'], 'They split responsibilities, not prices.'),
          FILL('Standard international trade terms are called ___.', ['Incoterms','tariffs','TEU'], 'Published by the International Chamber of Commerce.') ]),
    ]},
    {t:'Risk and strategy', lessons:[
      L('Just-in-time vs. just-in-case',
        'Just-in-time (JIT) keeps little inventory and gets parts right when they’re needed. It is cheap but fragile. Just-in-case holds extra safety stock. It costs more but survives shocks like the 2021 chip shortage.',
        [ MC('Which strategy keeps minimal inventory?', ['Just-in-time','Just-in-case','Stockpiling'], 'Parts arrive as they’re needed.'),
          TF('Just-in-time supply chains are more exposed to sudden disruptions.', true, 'There’s no buffer when a shipment is late.'),
          FILL('Extra inventory held for surprises is called safety ___.', ['stock','net','margin'], 'Safety stock.'),
          MATCH([['Just-in-time','Parts arrive when needed'],['Just-in-case','Hold extra to absorb shocks'],['Safety stock','Buffer inventory'],['Lead time','Time from order to delivery']]),
          MC('A supplier’s lead time grows from 4 to 10 weeks. What should you do?', ['Order earlier or hold more stock','Cut safety stock','Nothing, it doesn’t matter'], 'Longer lead times need earlier orders or bigger buffers.') ]),
      L('The bullwhip effect',
        'Small changes in customer demand grow bigger at each step up the chain, as retailers, distributors and factories each over-order to be safe. Sharing real sales data up the chain reduces the whipsaw.',
        [ MC('Shoppers buy 5% more. The factory sees orders jump 40%. This is…', ['The bullwhip effect','Inflation','A trade deficit'], 'Each stage amplifies the signal.'),
          TF('Sharing real-time sales data with suppliers can reduce the bullwhip effect.', true, 'Everyone plans from the same real demand.'),
          FILL('Demand swings that grow larger up the chain are the ___ effect.', ['bullwhip','network','halo'], 'Like cracking a whip.'),
          MC('Which makes the bullwhip effect worse?', ['Each stage ordering extra “just to be safe”','Stable, shared forecasts','Smaller, more frequent orders'], 'Padding orders at every stage compounds.'),
          ORDER('Order from smallest to largest demand swings', ['Customer','Retailer','Distributor','Manufacturer'], 'Swings grow as you move away from the customer.') ]),
      L('Trade, tariffs and sourcing',
        'A tariff is a tax on imports. Customs classifies goods with HS codes to set the duty. Companies reduce risk by buying from several countries or by moving production closer to their customers, which is called nearshoring.',
        [ MATCH([['Tariff','Tax on imported goods'],['HS code','Customs product classification'],['Nearshoring','Producing closer to customers'],['Dual sourcing','Two suppliers for one part']]),
          MC('A 25% tariff on a $100 import adds…', ['$25','$2.50','$125'], '25% of $100.'),
          TF('Relying on a single supplier in one country is the lowest-risk setup.', false, 'One disruption can stop everything.'),
          MC('A US company moves a factory from Asia to Mexico. That is…', ['Nearshoring','Offshoring','Vertical integration'], 'Closer to its home market.'),
          FILL('Customs uses ___ codes to classify products.', ['HS','TEU','SKU'], 'Harmonized System codes.') ]),
    ]},
  ]
},
];
/* ---------- Units 3 and 4 for every course ---------- */
const MORE = {
invest: [
  {t:'Beyond stocks', lessons:[
    L('Bonds',
      'A bond is a loan you make to a government or company. It pays regular interest, called the coupon, and returns your money at maturity. When interest rates rise, existing bond prices fall, because new bonds pay more.',
      [ MC('When you buy a bond, you are…', ['Lending money to the issuer','Buying part of the company','Paying an insurance premium'], 'Bondholders are lenders, not owners.'),
        FILL('The regular interest a bond pays is called the ___.', ['coupon','dividend','premium'], 'Coupon payments are usually fixed.'),
        TF('When interest rates rise, prices of existing bonds usually fall.', true, 'Older bonds pay less than new ones, so they are worth less.'),
        MATCH([['Coupon','Regular interest payment'],['Maturity','Date the loan is repaid'],['Issuer','Who borrows the money'],['Credit rating','Grade of the issuer’s ability to repay']]),
        MC('Which bond usually pays the higher interest rate?', ['A company with a low credit rating','A government with a top credit rating','Both pay the same'], 'Riskier borrowers must pay more to attract lenders.') ]),
    L('Reading an earnings report',
      'Each quarter, public companies report revenue, profit and earnings per share (EPS). EPS = net income ÷ shares outstanding. Prices often move on whether results beat or miss expectations and on guidance, the company’s own forecast.',
      [ MC('A company earns $10 million with 5 million shares. EPS is…', ['$2','$0.50','$50'], '$10,000,000 ÷ 5,000,000 = $2.'),
        FILL('A company’s own forecast for coming quarters is called ___.', ['guidance','coupon','leverage'], 'Weak guidance can sink a stock even after good results.'),
        TF('A stock can fall even when the company reports record profits.', true, 'If results or guidance miss what investors expected, the price can drop.'),
        MATCH([['Revenue','Total sales'],['Net income','Profit after all costs'],['EPS','Profit per share'],['YoY','Compared with a year earlier']]),
        MC('Analysts expected EPS of $1.20. The company reports $1.35. This is…', ['A beat','A miss','In line'], 'It came in above expectations.') ], '#AAPL'),
    L('What is a stock worth?',
      'Valuation asks whether a price makes sense. The P/E ratio compares price with earnings. Price-to-sales (P/S) helps for companies without profits. Growth stocks trade at high multiples on future hopes; value stocks trade at low multiples.',
      [ MC('A $50 stock with $2.50 of yearly EPS has a P/E of…', ['20','125','2.5'], '$50 ÷ $2.50 = 20.'),
        MC('Which ratio helps value a company that has no profits yet?', ['Price-to-sales','P/E','Dividend yield'], 'P/E doesn’t work when earnings are zero or negative.'),
        TF('A low P/E always means a stock is a bargain.', false, 'It can also signal trouble or slowing growth.'),
        MATCH([['Growth stock','High multiple, fast expected growth'],['Value stock','Low multiple, steady business'],['P/E','Price ÷ earnings per share'],['P/S','Price ÷ sales per share']]),
        FILL('Investors pay high multiples for ___ stocks expected to expand quickly.', ['growth','value','penny'], 'They are paying for future earnings.') ], '#NVDA'),
  ]},
  {t:'Investing for life', lessons:[
    L('Retirement accounts',
      'Retirement accounts give tax advantages for long-term saving. In the US, a 401(k) comes through your employer, and many employers match part of what you put in. An IRA is one you open yourself. Roth accounts are taxed now and withdrawn tax-free later.',
      [ MC('Your employer matches 401(k) contributions up to 4% of pay. What should you usually do first?', ['Contribute at least 4% to get the full match','Skip it and invest on your own','Wait until you’re older'], 'An employer match is money you don’t get otherwise.'),
        MATCH([['401(k)','Employer retirement plan'],['IRA','Account you open yourself'],['Roth','Pay tax now, tax-free later'],['Employer match','Company adds to your savings']]),
        TF('Starting to save at 25 instead of 35 can make a big difference by retirement.', true, 'Ten extra years of compounding adds up.'),
        FILL('An account taxed now and withdrawn tax-free in retirement is a ___ account.', ['Roth','traditional','checking'], 'Roth: pay the tax up front.'),
        MC('Why are retirement accounts useful?', ['They give tax advantages for long-term saving','They guarantee returns','They can’t lose value'], 'Investments inside them can still go up and down.') ], '#tools'),
    L('Taxes on investments',
      'Selling for more than you paid creates a capital gain, which is taxed. In the US, gains on investments held more than a year are long-term and usually taxed less than short-term gains. Dividends are usually taxed too.',
      [ MC('In the US, a stock held for more than one year and then sold creates a…', ['Long-term capital gain','Short-term capital gain','Tax-free gain'], 'Holding longer than a year usually means lower rates.'),
        TF('You owe capital gains tax on a stock that rose but that you haven’t sold.', false, 'Gains are usually taxed when you sell, not while you hold.'),
        FILL('Profit from selling an investment for more than you paid is a capital ___.', ['gain','loss','yield'], 'Capital gain.'),
        MATCH([['Short-term gain','Held one year or less'],['Long-term gain','Held more than one year'],['Capital loss','Sold below purchase price'],['Tax-loss harvesting','Selling losers to offset gains']]),
        MC('Why do some investors avoid selling winners too quickly?', ['Holding longer can lower the tax rate','Selling is illegal before a year','Brokers forbid it'], 'Short-term gains are often taxed like regular income.') ]),
    L('Your brain on money',
      'The biggest risk is often behavior. Fear of missing out (FOMO) leads to buying high. Panic leads to selling low. Loss aversion makes losses feel about twice as painful as equal gains. A written plan and patience beat emotional decisions.',
      [ MC('A stock jumps 40% in a week and everyone online is buying. The risk is…', ['FOMO: buying near a peak','Diversification','Too much caution'], 'Chasing hype often means paying top prices.'),
        TF('Selling everything during a market crash usually protects long-term returns.', false, 'Panic selling locks in losses and often misses the rebound.'),
        MATCH([['FOMO','Buying from fear of missing out'],['Loss aversion','Losses hurt more than gains feel good'],['Overconfidence','Thinking you can’t be wrong'],['Herding','Doing what everyone else does']]),
        FILL('“Time in the market beats ___ the market.”', ['timing','beating','leaving'], 'Staying invested usually beats jumping in and out.'),
        MC('What helps most against emotional investing?', ['A written plan you follow','Checking prices every hour','Following social media tips'], 'Decide in calm times what you’ll do in stormy ones.') ], '#portfolio'),
  ]},
],
trading: [
  {t:'Market dynamics', lessons:[
    L('Volume and volatility',
      'Volume is how many shares trade. Big moves on high volume are more convincing than moves on low volume. Volatility measures how much price swings. A gap is when a stock opens far from the previous close, often after news.',
      [ MC('A stock breaks out above resistance on twice its normal volume. This suggests…', ['The move has strong participation','The move is meaningless','Trading was halted'], 'Volume confirms conviction.'),
        TF('Higher volatility means bigger potential gains and bigger potential losses.', true, 'Swings cut both ways.'),
        FILL('When a stock opens far above yesterday’s close, it ___ up.', ['gapped','split','drifted'], 'Gaps often follow earnings or news.'),
        MATCH([['Volume','Shares traded in a period'],['Volatility','How much price swings'],['Gap','Open far from prior close'],['Liquidity','How easily you can trade']]),
        MC('Which usually swings the most?', ['A small biotech stock','An S&P 500 index fund','A large soft-drink company'], 'Biotech prices can jump or crash on a single trial result; broad index funds swing the least.') ], '#MRNA'),
    L('Momentum vs. mean reversion',
      'Momentum traders bet that strong trends continue. Mean-reversion traders bet that stretched prices snap back toward their average. Both can work, in different markets and time frames, and both need risk limits.',
      [ MC('Buying a stock because it keeps making new highs is a…', ['Momentum strategy','Mean-reversion strategy','Dividend strategy'], 'Riding the trend.'),
        MC('Buying a stock that dropped far below its average, expecting a bounce, is…', ['Mean reversion','Momentum','Arbitrage'], 'Betting on a return to the mean.'),
        TF('A strategy that works in trending markets can struggle in choppy, sideways markets.', true, 'Market conditions change which approach works.'),
        MATCH([['Momentum','Trends tend to continue'],['Mean reversion','Extremes tend to snap back'],['Trend','Persistent direction of price'],['Range','Price bouncing between levels']]),
        FILL('Prices bouncing between support and resistance are in a ___.', ['range','trend','gap'], 'Range-bound markets favor mean reversion.') ]),
    L('Short selling',
      'Short selling bets on a price falling. You borrow shares, sell them, and hope to buy them back cheaper. If the price rises instead, losses have no ceiling. A short squeeze is when rising prices force short sellers to buy, pushing prices higher.',
      [ MC('You short at $50 and buy back at $40. Your profit per share is…', ['$10','−$10','$90'], 'Sell high first, buy low later.'),
        TF('A short seller’s maximum possible loss is limited.', false, 'A price can keep rising, so losses are theoretically unlimited.'),
        FILL('When short sellers rush to buy back and push the price up, it’s a short ___.', ['squeeze','sale','spread'], 'Buying begets more buying.'),
        MATCH([['Short sale','Sell borrowed shares'],['Cover','Buy back to close a short'],['Short squeeze','Forced buying drives price up'],['Borrow fee','Cost to borrow shares']]),
        MC('Why is short selling considered high risk?', ['Losses can exceed what you put in','It’s illegal','It only works in bull markets'], 'Use strict stops if you ever short.') ]),
  ]},
  {t:'Options and mindset', lessons:[
    L('What is an option?',
      'An option is a contract giving the right, not the obligation, to buy or sell a stock at a set price (the strike) before a date (expiration). A call is the right to buy; a put is the right to sell. You pay a premium for it. A US stock option usually covers 100 shares.',
      [ MATCH([['Call','Right to buy at the strike'],['Put','Right to sell at the strike'],['Strike','Price set in the contract'],['Premium','Price you pay for the option']]),
        MC('You expect a stock to rise. Which option fits?', ['A call','A put','Neither'], 'Calls gain when the price goes up.'),
        TF('Buying an option obligates you to buy the shares.', false, 'The buyer has the right, not the obligation.'),
        FILL('The date an option stops being valid is its ___.', ['expiration','maturity','settlement'], 'After expiration, the right is gone.'),
        MC('A typical US stock option contract covers…', ['100 shares','1 share','1,000 shares'], 'So a $2 premium costs $200 per contract.') ]),
    L('Option payoffs',
      'If you buy an option, the most you can lose is the premium. A call is profitable at expiration if the stock ends above strike + premium. Options can lose value fast as expiration nears, which is called time decay.',
      [ MC('You pay $3 for a call with a $50 strike. The break-even price at expiration is…', ['$53','$50','$47'], 'Strike + premium = $53.'),
        MC('The most an option buyer can lose is…', ['The premium paid','Unlimited','The strike price'], 'If it expires worthless, you lose the premium.'),
        TF('Options tend to lose value as expiration approaches, all else equal.', true, 'That’s time decay.'),
        FILL('The loss of option value as time passes is time ___.', ['decay','value','spread'], 'Also called theta.'),
        MC('A put with a $40 strike, stock at $30 at expiration. Its value per share is…', ['$10','$0','$30'], 'Right to sell at $40 when it’s worth $30.') ]),
    L('Trading psychology',
      'Most trading mistakes are emotional: overtrading, revenge trading after a loss, and moving stops. Pros use a written plan, keep a trading journal, and judge themselves on following the plan, not on any single result.',
      [ MC('After a loss, you instantly double your next trade to win it back. That’s…', ['Revenge trading','Position sizing','Hedging'], 'A fast way to turn one loss into many.'),
        TF('Moving your stop-loss further away when a trade goes against you is good discipline.', false, 'It lets small losses become big ones.'),
        FILL('A written record of every trade and why you took it is a trading ___.', ['journal','ledger','ticket'], 'Reviewing it reveals patterns.'),
        ORDER('Order a healthy trading routine', ['Write the plan','Take the trade','Log it in your journal','Review weekly'], 'Plan, act, record, learn.'),
        MC('What should you judge a single trade on?', ['Whether you followed your plan','Only whether it made money','How exciting it was'], 'Good process wins over time; single results are noisy.') ], '#portfolio'),
  ]},
],
money: [
  {t:'Earning and taxes', lessons:[
    L('Your paycheck',
      'Gross pay is what you earn before deductions. Net pay, or take-home pay, is what lands in your account after taxes, retirement contributions and benefits like health insurance are taken out.',
      [ MC('Salary is $4,000 a month; $900 is withheld. Net pay is…', ['$3,100','$4,900','$4,000'], '$4,000 − $900.'),
        MATCH([['Gross pay','Earnings before deductions'],['Net pay','Take-home pay'],['Withholding','Tax taken from each check'],['Pre-tax deduction','Taken out before tax, like 401(k)']]),
        TF('Budgets should be built on net pay, not gross pay.', true, 'Net pay is what you can actually spend.'),
        FILL('Money taken from each paycheck for taxes is called ___.', ['withholding','interest','equity'], 'It prepays your yearly tax bill.'),
        MC('Why does a 401(k) contribution lower your taxable pay?', ['It’s often taken out before tax','It’s a tax credit','It’s a gift from the government'], 'Traditional contributions are usually pre-tax.') ]),
    L('How taxes work',
      'Many countries, including the US, tax income in brackets. Your marginal rate applies only to the income inside each higher bracket, not all of it. A deduction lowers your taxable income; a credit lowers your tax bill dollar for dollar.',
      [ TF('A raise that moves you into a higher bracket can lower your take-home pay.', false, 'Only the dollars above the threshold are taxed at the higher rate.'),
        MATCH([['Marginal rate','Rate on your last dollar'],['Effective rate','Total tax ÷ total income'],['Deduction','Lowers taxable income'],['Credit','Lowers tax owed directly']]),
        MC('Which saves more, if you’re in a 22% bracket?', ['A $1,000 tax credit','A $1,000 deduction','They’re equal'], 'The credit saves $1,000; the deduction saves about $220.'),
        FILL('Your total tax divided by your total income is your ___ tax rate.', ['effective','marginal','flat'], 'Usually lower than your marginal rate.'),
        MC('Why do tax brackets matter for planning?', ['They show how much of each extra dollar you keep','They set your salary','They decide your credit score'], 'Your marginal rate tells you the tax on extra income.') ]),
    L('Side income',
      'Freelance and gig income usually has no tax withheld. Many freelancers set aside a portion of each payment, often 25–30%, for taxes, track business expenses, and keep business money in a separate account.',
      [ MC('You earn $1,000 freelancing with nothing withheld. A common habit is to…', ['Set aside a portion for taxes','Spend it all now','Ignore it until next year'], 'Taxes are still due on it.'),
        TF('Keeping a separate account for side-income money makes taxes and tracking easier.', true, 'It keeps business and personal spending apart.'),
        FILL('Costs of running your side business may be tax-___.', ['deductible','exempt','free'], 'Keep receipts.'),
        MATCH([['Freelance income','Paid per project'],['Business expense','Cost to earn the income'],['Estimated taxes','Paying tax during the year'],['Receipt','Proof of an expense']]),
        MC('What’s the risk of not saving for taxes on side income?', ['A big surprise bill later','Higher credit score','Lower rent'], 'Plan for it from the first payment.') ], '#tools'),
  ]},
  {t:'Protecting what you have', lessons:[
    L('Insurance basics',
      'Insurance swaps a small, certain cost (the premium) for protection against a big, uncertain one. The deductible is what you pay before insurance pays. A higher deductible usually means a lower premium.',
      [ MATCH([['Premium','What you pay for coverage'],['Deductible','What you pay before coverage starts'],['Claim','Request for the insurer to pay'],['Coverage','What the policy protects']]),
        MC('Deductible $500. A covered repair costs $2,000. Insurance pays about…', ['$1,500','$2,000','$500'], 'You pay the first $500.'),
        TF('Raising your deductible usually lowers your premium.', true, 'You take on more of the small risks yourself.'),
        FILL('The regular payment you make to keep insurance active is the ___.', ['premium','deductible','claim'], 'Premiums are paid monthly or yearly.'),
        MC('Insurance makes the most sense for…', ['Losses you couldn’t afford to cover yourself','Tiny, everyday costs','Guaranteed profits'], 'Protect against the big hits.') ]),
    L('Renting vs. buying',
      'Buying builds equity but needs a down payment, closing costs and upkeep. Renting keeps you flexible. A common guide is keeping housing costs under about 28% of gross income. In the US, putting down less than 20% on a conventional loan usually means paying mortgage insurance (PMI).',
      [ MC('Gross income is $6,000 a month. The 28% guide suggests housing costs up to about…', ['$1,680','$2,800','$600'], '28% of $6,000.'),
        MATCH([['Down payment','Cash paid upfront'],['Mortgage','Loan to buy a home'],['Equity','The part of the home you own'],['PMI','Insurance for low down payments']]),
        TF('Renting is always throwing money away.', false, 'Renting buys flexibility and avoids repairs and big upfront costs.'),
        FILL('The share of your home you truly own is your ___.', ['equity','principal','escrow'], 'It grows as you pay down the loan.'),
        MC('Which cost do buyers often forget?', ['Maintenance and repairs','Rent','Security deposit'], 'A common guide is 1–2% of the home’s value per year.') ]),
    L('Spotting scams',
      'Scams promise guaranteed high returns, create urgency, and ask for payment in gift cards, crypto or wire transfers. Real firms never ask for your password. If it sounds too good to be true, it almost certainly is.',
      [ MC('“Guaranteed 20% a month, act today!” This is most likely…', ['A scam','A great deal','A government bond'], 'Guarantees plus urgency are classic red flags.'),
        TF('Your bank may ask you to share your password by text to “verify” your account.', false, 'Legitimate firms never ask for your password.'),
        MATCH([['Phishing','Fake message stealing logins'],['Ponzi scheme','Old investors paid with new money'],['Pump and dump','Hype a stock, then sell'],['Impersonation','Pretending to be a trusted company']]),
        FILL('A fake email designed to steal your login is called ___.', ['phishing','hedging','vesting'], 'Check the sender and never click unknown links.'),
        MC('A “broker” wants payment in gift cards. You should…', ['Refuse and report it','Pay quickly before the deal ends','Send half now'], 'Real businesses don’t take gift cards for investments.') ]),
  ]},
],
biz: [
  {t:'Growth marketing', lessons:[
    L('Building a brand',
      'A brand is what people feel and expect when they see your name. It’s built through consistency: the same look, voice and promise everywhere. A logo is part of a brand, but the brand is the whole experience.',
      [ TF('A brand is just a logo.', false, 'It’s the whole experience and reputation.'),
        MATCH([['Brand identity','Logo, colors, type'],['Brand voice','How the brand speaks'],['Brand promise','What customers can count on'],['Brand equity','Value the name adds']]),
        MC('Which builds a brand fastest?', ['Consistency across every touchpoint','Changing the logo often','Copying competitors'], 'Recognition comes from repetition.'),
        FILL('The personality in how a brand writes and speaks is its brand ___.', ['voice','equity','funnel'], 'Toro’s voice is calm and confident.'),
        MC('Why can strong brands charge more?', ['Customers trust them and value the name','They have lower costs','They advertise less'], 'Trust is worth paying for.') ]),
    L('Pricing strategy',
      'Cost-plus pricing adds a markup to cost. Value-based pricing charges what customers think it’s worth. Penetration pricing starts low to win market share. Skimming starts high and lowers over time. $9.99 instead of $10 is psychological pricing.',
      [ MATCH([['Cost-plus','Cost plus a markup'],['Value-based','Priced on customer value'],['Penetration','Start low to win share'],['Skimming','Start high, lower later']]),
        MC('A new gadget launches at $999 and drops to $699 a year later. This is…', ['Skimming','Penetration','Cost-plus'], 'Early buyers pay more.'),
        MC('A product costs $20 to make and sells with a 50% markup. The price is…', ['$30','$40','$25'], '$20 + 50% of $20.'),
        TF('Pricing at $9.99 instead of $10 is an example of psychological pricing.', true, 'It feels meaningfully cheaper.'),
        FILL('Starting with a low price to grab customers is ___ pricing.', ['penetration','premium','skimming'], 'Common for new streaming services.') ]),
    L('Digital marketing',
      'Digital channels include search (SEO), content, social media and email. Key numbers: click-through rate (CTR) = clicks ÷ impressions, and CPM = cost per 1,000 impressions. Email you own; social reach can change overnight.',
      [ MC('An ad is seen 10,000 times and clicked 200 times. CTR is…', ['2%','20%','0.2%'], '200 ÷ 10,000.'),
        MATCH([['SEO','Ranking in search results'],['CTR','Clicks ÷ impressions'],['CPM','Cost per 1,000 impressions'],['Email list','Audience you own directly']]),
        TF('An email list is less dependent on platform algorithm changes than social followers.', true, 'You own the relationship.'),
        FILL('Improving a site so it ranks higher in search is ___.', ['SEO','CPM','ROI'], 'Search engine optimization.'),
        MC('You spend $500 for 100,000 impressions. The CPM is…', ['$5','$50','$0.50'], '$500 ÷ 100 thousands.') ]),
  ]},
  {t:'Running the company', lessons:[
    L('Reading a P&L',
      'A profit and loss statement (P&L) runs from revenue down to net income. Subtract cost of goods sold (COGS) to get gross profit. Subtract operating expenses like salaries and rent to get operating profit. Subtract interest and taxes to get net income.',
      [ ORDER('Order the lines of a P&L', ['Revenue','Gross profit','Operating profit','Net income'], 'Top line to bottom line.'),
        MC('Revenue $100,000, COGS $40,000. Gross profit is…', ['$60,000','$140,000','$40,000'], '$100,000 − $40,000.'),
        MATCH([['COGS','Direct cost of what you sold'],['Gross profit','Revenue minus COGS'],['Operating expenses','Rent, salaries, marketing'],['Net income','The bottom line']]),
        TF('“Top line” means revenue and “bottom line” means net income.', true, 'They sit at the top and bottom of the P&L.'),
        FILL('Direct costs of making what you sold are cost of goods ___.', ['sold','bought','made'], 'COGS.') ]),
    L('Cash is king',
      'Profit and cash are different. A business can be profitable on paper and still run out of cash if customers pay late. Burn rate is how much cash a company spends each month. Runway = cash ÷ monthly burn.',
      [ MC('$300,000 in the bank, burning $25,000 a month. Runway is…', ['12 months','25 months','3 months'], '$300,000 ÷ $25,000.'),
        TF('A profitable company can still run out of cash.', true, 'If customers pay slowly, cash can run dry.'),
        MATCH([['Burn rate','Cash spent per month'],['Runway','Months until cash runs out'],['Receivables','Money customers owe you'],['Cash flow','Money moving in and out']]),
        FILL('Money customers owe you for sales already made is accounts ___.', ['receivable','payable','equity'], 'Collect it quickly.'),
        MC('Which improves cash flow fastest?', ['Getting customers to pay sooner','Buying more inventory','Paying suppliers early'], 'Cash in sooner, out later.') ]),
    L('Pitching and funding',
      'Startups can bootstrap (grow from their own revenue), raise from angels (individuals) or from venture capital (funds). Selling equity dilutes founders’ ownership. Post-money valuation = pre-money valuation + new investment.',
      [ MC('Pre-money valuation $4M, investment $1M. Post-money is…', ['$5M','$3M','$4M'], '$4M + $1M.'),
        MC('In that deal, the investor owns about…', ['20%','25%','10%'], '$1M ÷ $5M.'),
        MATCH([['Bootstrapping','Growing from your own revenue'],['Angel investor','Individual backing early startups'],['Venture capital','Funds investing for high growth'],['Dilution','Owning a smaller share after new shares']]),
        TF('Raising money by selling equity reduces the founders’ ownership percentage.', true, 'That’s dilution.'),
        FILL('A short, persuasive presentation to investors is a ___ deck.', ['pitch','balance','trading'], 'Problem, solution, market, team, ask.') ]),
  ]},
],
supply: [
  {t:'Inside the warehouse', lessons:[
    L('Inventory math',
      'The reorder point tells you when to order: daily demand × lead time + safety stock. Economic order quantity (EOQ) balances the cost of ordering against the cost of holding stock. Inventory turnover = cost of goods sold ÷ average inventory.',
      [ MC('You sell 20 units a day, lead time is 5 days, safety stock is 30. Reorder point is…', ['130 units','100 units','25 units'], '20 × 5 + 30.'),
        MATCH([['Reorder point','Stock level that triggers an order'],['Lead time','Days from order to arrival'],['EOQ','Order size that minimizes total cost'],['Turnover','How often inventory sells through']]),
        TF('High inventory turnover usually means stock sells quickly.', true, 'Less cash sits on shelves.'),
        MC('COGS $600,000, average inventory $100,000. Turnover is…', ['6 times','60 times','0.6 times'], '$600,000 ÷ $100,000.'),
        FILL('EOQ balances ordering costs against ___ costs.', ['holding','shipping','marketing'], 'Storing stock costs money too.') ]),
    L('Warehousing and fulfillment',
      'Warehouses receive, store, pick, pack and ship. Cross-docking moves goods from inbound to outbound trucks with little or no storage. Many brands outsource this to a third-party logistics provider (3PL). Each distinct product version has its own SKU.',
      [ ORDER('Order the fulfillment steps', ['Receive','Store','Pick','Pack','Ship'], 'From dock to customer.'),
        MATCH([['SKU','Code for one product version'],['3PL','Outsourced logistics partner'],['Cross-docking','Transfer without storing'],['Pick and pack','Gathering and boxing orders']]),
        TF('A red T-shirt in size M and a blue one in size M usually have different SKUs.', true, 'Each variant gets its own code.'),
        FILL('A company you pay to store and ship your products is a ___.', ['3PL','CPM','SKU'], 'Third-party logistics.'),
        MC('Cross-docking mainly reduces…', ['Storage time','Product quality','Marketing costs'], 'Goods barely stop.') ]),
    L('The last mile',
      'The last mile, from the local hub to the customer’s door, is often the most expensive part of delivery. Companies cut costs with route optimization, parcel lockers and delivery windows. Handling returns is called reverse logistics.',
      [ TF('The last mile is often the most expensive leg of delivery per package.', true, 'Many stops, few packages each.'),
        MATCH([['Last mile','Hub to customer’s door'],['Reverse logistics','Handling returns'],['Route optimization','Planning efficient stops'],['Parcel locker','Pickup point for packages']]),
        MC('Which cuts last-mile cost?', ['Grouping deliveries into efficient routes','Sending each package separately','Shipping by air across town'], 'Denser routes, lower cost per stop.'),
        FILL('Managing products customers send back is ___ logistics.', ['reverse','forward','inbound'], 'Returns flow backward.'),
        MC('Why do shops offer free returns despite the cost?', ['It raises buyer confidence and sales','Returns are free to process','Law requires it everywhere'], 'Easier returns can mean more orders.') ]),
  ]},
  {t:'Global trade today', lessons:[
    L('Procurement and negotiation',
      'Procurement is how companies buy. A request for quotation (RFQ) invites suppliers to bid. Smart buyers compare total cost of ownership (price plus shipping, duties, quality issues and delays), not just unit price. Suppliers often set a minimum order quantity (MOQ).',
      [ MATCH([['RFQ','Invitation for suppliers to quote'],['MOQ','Smallest order a supplier accepts'],['TCO','Full cost beyond the price tag'],['Scorecard','Rating supplier performance']]),
        MC('Supplier A: $10/unit, often late. Supplier B: $11/unit, reliable. Which may cost less overall?', ['Possibly B, once delays are counted','Always A','They cost the same'], 'Late parts can halt production.'),
        TF('The lowest unit price is always the best deal.', false, 'Shipping, duties, quality and delays add up.'),
        FILL('A supplier that only accepts orders of 1,000+ units has an ___ of 1,000.', ['MOQ','RFQ','SKU'], 'Minimum order quantity.'),
        MC('What’s a benefit of a supplier scorecard?', ['It tracks quality, delivery and cost over time','It sets retail prices','It replaces contracts'], 'Measure to manage.') ]),
    L('Sustainable supply chains',
      'Companies report emissions in three scopes. Scope 1 is direct emissions, Scope 2 comes from purchased energy, and Scope 3 is everything else in the value chain, often the largest share. A circular economy designs out waste through reuse and recycling.',
      [ MATCH([['Scope 1','Direct emissions'],['Scope 2','Purchased electricity and energy'],['Scope 3','Rest of the value chain'],['Circular economy','Designing out waste']]),
        TF('For many companies, Scope 3 is the largest share of emissions.', true, 'Suppliers and product use add up.'),
        MC('Switching a warehouse to renewable electricity mainly cuts…', ['Scope 2','Scope 1','Scope 3'], 'Scope 2 covers purchased energy.'),
        FILL('An economy built on reuse, repair and recycling is ___.', ['circular','linear','closed'], 'Keep materials in use.'),
        MC('Moving freight from air to ocean generally…', ['Lowers emissions per unit','Raises emissions','Changes nothing'], 'Ships emit far less per ton-mile than planes.') ], '#FDX'),
    L('Ports and disruptions',
      'Most goods pass through a few chokepoints like the Suez and Panama Canals and the Strait of Malacca. In March 2021 the ship Ever Given blocked the Suez Canal for six days, holding up hundreds of ships. Port congestion creates delays and fees like demurrage.',
      [ MC('Which is a major shipping chokepoint?', ['Suez Canal','Lake Tahoe','The Thames Barrier'], 'It links Asia and Europe.'),
        TF('In 2021, one stuck ship blocked the Suez Canal for about six days.', true, 'The Ever Given held up hundreds of vessels.'),
        MATCH([['Chokepoint','Narrow route much trade depends on'],['Congestion','Too many ships, too little capacity'],['Demurrage','Fee for containers kept too long'],['Rerouting','Taking a longer alternative route']]),
        FILL('A fee charged when containers stay at the port too long is ___.', ['demurrage','tariff','insurance'], 'Delays cost money.'),
        MC('A chokepoint closes for weeks. What helps most?', ['Diversified routes and safety stock','Cutting inventory to zero','Ignoring it'], 'Resilience comes from options and buffers.') ], '#UPS'),
  ]},
],
};
for (const c of window.TORO_COURSES) if (MORE[c.id]) c.units.push(...MORE[c.id]);
})();
