/* Toro course content.
 *
 * Each course has units, each unit has lessons, each lesson has a short tip and five questions.
 * Authoring rule: for MC and FILL, the FIRST option is the correct one. The app shuffles options.
 * ORDER lists items in the correct order. MATCH lists [term, meaning] pairs.
 * `apply` (optional) links a lesson to a place in the app to practice it, e.g. '#KSTL' or '#tools'.
 */
(function(){
const MC    = (q, o, why) => ({t:'mc', q, o, why});
const TF    = (q, a, why) => ({t:'tf', q, a, why});
const FILL  = (q, o, why) => ({t:'fill', q, o, why});
const MATCH = (pairs, why) => ({t:'match', q:'Match each term to its meaning', pairs, why});
const ORDER = (q, items, why) => ({t:'order', q, items, why});
const L = (t, tip, qs, apply) => ({t, tip, qs, apply});

window.TORO_COURSES = [
{
  id:'invest', name:'Stocks & Investing', color:'#1F9D63',
  blurb:'What stocks are, why prices move, and how to build a portfolio that lasts.',
  units:[
    {t:'Owning a piece of a company', lessons:[
      L('What is a stock?',
        'A stock, or share, is a small slice of ownership in a company. If you own shares you are a shareholder: you share in the company’s profits and its losses. Each stock has a short code called a ticker, like LUMQ on Toro.',
        [ MC('What do you own when you buy a share of stock?', ['A small piece of the company','A loan to the company','A coupon for its products'], 'A share is partial ownership. Lending money to a company is a bond.'),
          TF('A ticker is the short code used to identify a stock, like LUMQ.', true, 'Tickers make stocks quick to look up and trade.'),
          FILL('People who own shares in a company are called ___.', ['shareholders','lenders','customers'], 'Shareholders are part-owners of the company.'),
          MATCH([['Stock','A slice of ownership'],['Ticker','Short code for a stock'],['Exchange','Marketplace where shares trade'],['Shareholder','Person who owns shares']]),
          MC('Where are shares of public companies bought and sold?', ['On a stock exchange','Only at company headquarters','At a bank vault'], 'Exchanges match buyers and sellers.') ], '#LUMQ'),
      L('Why prices move',
        'Buyers and sellers set a stock’s price. When more people want to buy than sell, the price rises. When more want to sell, it falls. Market capitalization is the total value of all the shares: price × number of shares.',
        [ MC('If far more people want to buy a stock than sell it, the price usually…', ['Rises','Falls','Stays the same'], 'Demand greater than supply pushes prices up.'),
          MC('A company has 10 million shares at $50 each. What is its market cap?', ['$500 million','$50 million','$5 billion'], '10,000,000 × $50 = $500,000,000.'),
          TF('A higher share price always means a bigger company.', false, 'Size is market cap. A $500 stock with few shares can be smaller than a $20 stock with billions of shares.'),
          FILL('Market cap = share price × number of ___.', ['shares','employees','customers'], 'Multiply price by shares outstanding.'),
          MC('Which news would most likely push a stock DOWN?', ['The company cuts its profit forecast','The company beats earnings expectations','The company wins a big contract'], 'Lower expected profits make shares less attractive.') ]),
      L('How investors get paid',
        'Investors make money in two ways. A capital gain is selling for more than you paid. A dividend is cash some companies pay out of their profits. Dividend yield = yearly dividend ÷ share price.',
        [ MATCH([['Capital gain','Profit from selling higher'],['Dividend','Cash paid out of profits'],['Dividend yield','Yearly dividend as % of price'],['Capital loss','Selling for less than you paid']]),
          MC('You buy at $40 and sell at $50. Your capital gain per share is…', ['$10','$50','$90'], '$50 − $40 = $10.'),
          MC('A stock costs $100 and pays $3 a year in dividends. What is the yield?', ['3%','30%','0.3%'], '$3 ÷ $100 = 3%.'),
          TF('Every company pays a dividend.', false, 'Many growing companies reinvest profits instead. Lumiq (LUMQ) on Toro pays none.'),
          FILL('Selling a stock for more than you paid creates a capital ___.', ['gain','loss','tax'], 'Sell high, buy low: that difference is the gain.') ], '#ORCF'),
    ]},
    {t:'Building a portfolio', lessons:[
      L('Don’t put all your eggs in one basket',
        'Diversification means spreading money across many companies and sectors. If one company has a bad year, the others soften the blow. It lowers risk without needing to predict winners.',
        [ MC('Which portfolio is most diversified?', ['20 stocks across 7 sectors','5 technology stocks','1 stock you really like'], 'More companies across more sectors spreads risk.'),
          TF('Diversification removes all risk.', false, 'It lowers company-specific risk, but the whole market can still fall.'),
          FILL('Spreading money across many investments is called ___.', ['diversification','leverage','speculation'], 'Diversify to reduce the damage from any one loser.'),
          MC('Why hold stocks from different sectors?', ['Sectors often react differently to the same news','It guarantees higher returns','It avoids all taxes'], 'High oil prices can hurt airlines but help energy producers.'),
          MC('80% of your portfolio is one stock. What is the main risk?', ['One bad result could hurt most of your money','You will pay too many fees','Your dividends will be too high'], 'Concentration ties your fate to one company.') ], '#portfolio'),
      L('Index funds and ETFs',
        'An index fund buys every company in an index, like Toro’s TXM. An ETF (exchange-traded fund) is a fund that trades like a stock. The expense ratio is the yearly fee, as a percentage of what you invest.',
        [ MATCH([['Index fund','Owns every stock in an index'],['ETF','Fund that trades like a stock'],['Expense ratio','Yearly fund fee as a %'],['Index','A list tracking a group of stocks']]),
          MC('You invest $10,000 in a fund with a 0.10% expense ratio. The yearly fee is about…', ['$10','$100','$1,000'], '0.10% of $10,000 = $10.'),
          TF('An index fund tries to match the market, not beat it.', true, 'That is why index funds are called passive investing.'),
          MC('What is a big advantage of an index fund for beginners?', ['Instant diversification at low cost','Guaranteed profits','No price swings'], 'One purchase spreads your money across the market.'),
          FILL('A fund that trades on an exchange like a stock is an ___.', ['ETF','IPO','APR'], 'ETF = exchange-traded fund.') ], '#TXM'),
      L('Time and compounding',
        'Compounding means your gains start earning gains of their own. The longer you stay invested, the bigger the effect. Money you need soon should take less risk than money you won’t touch for 20 years.',
        [ MC('$1,000 grows 10% a year. After 2 years it is worth…', ['$1,210','$1,200','$1,100'], 'Year 1: $1,100. Year 2: $1,100 × 1.10 = $1,210. The extra $10 is compounding.'),
          TF('Money you need next month is usually better kept out of stocks.', true, 'Stocks can drop sharply over short periods.'),
          ORDER('Order from lowest to highest typical risk', ['Savings account','Bond fund','Index fund','Single small biotech stock'], 'Fewer, riskier holdings mean bigger swings.'),
          FILL('Earning returns on your past returns is called ___.', ['compounding','hedging','shorting'], 'Growth on growth.'),
          MC('Rule of 72: at 8% a year, money doubles in about…', ['9 years','72 years','8 years'], '72 ÷ 8 = 9.') ], '#tools'),
    ]},
  ]
},
{
  id:'trading', name:'Trading', color:'#3F7CD6',
  blurb:'Order types, reading charts, and the risk rules traders live by.',
  units:[
    {t:'Placing orders', lessons:[
      L('Market and limit orders',
        'A market order fills right away at the best available price. A limit order sets your price: a buy limit fills at your price or lower, a sell limit at your price or higher. A limit order might never fill.',
        [ MC('You want to buy right now, whatever the price. Use a…', ['Market order','Limit order','Stop order'], 'Market orders trade immediately.'),
          MC('KSTL is at $142. You place a buy limit at $135. When does it fill?', ['When the price falls to $135 or lower','Right away at $142','Never, limit orders can’t buy'], 'A buy limit waits for your price or better.'),
          TF('A limit order guarantees your trade will happen.', false, 'It guarantees the price, not the fill.'),
          FILL('A sell limit fills at your price or ___.', ['higher','lower','never'], 'Sellers want the same or better, which means higher.'),
          MATCH([['Market order','Fills now at current price'],['Buy limit','Fills at your price or lower'],['Sell limit','Fills at your price or higher'],['Fill','When an order executes']]) ], '#KSTL'),
      L('Stop orders',
        'A stop-loss order sells automatically if the price falls to a level you set, capping your loss. When the stop price is hit it becomes a market order. A stop-limit becomes a limit order instead: it controls the price but might not fill.',
        [ MC('You bought at $50 and want to cap your loss near 10%. Where is your stop?', ['$45','$55','$40'], '10% below $50 is $45.'),
          TF('When a stop-loss triggers, it becomes a market order.', true, 'That is why it can fill below your stop in a fast drop.'),
          MC('What is the risk of a stop-limit order in a fast drop?', ['It may not fill at all','It sells at a huge premium','It buys more shares'], 'If the price gaps below your limit, nothing sells.'),
          FILL('An order that sells automatically to cap losses is a ___.', ['stop-loss','limit buy','margin call'], 'Set it when you enter the trade.'),
          MC('Why do traders use stop-losses?', ['To decide their exit before emotions kick in','To guarantee profits','To avoid paying the spread'], 'Planning the exit in advance keeps decisions calm.') ]),
      L('Spread and liquidity',
        'The bid is the highest price buyers will pay. The ask is the lowest price sellers will accept. The gap is the spread. Liquid stocks trade a lot and have tight spreads. Slippage is getting a worse price than you expected.',
        [ MATCH([['Bid','Highest price a buyer offers'],['Ask','Lowest price a seller accepts'],['Spread','Gap between bid and ask'],['Slippage','Filling at a worse price']]),
          MC('Bid $19.95, ask $20.05. The spread is…', ['$0.10','$0.05','$20.00'], '$20.05 − $19.95 = $0.10.'),
          TF('Stocks that trade in huge volumes usually have wider spreads.', false, 'Heavy trading usually means tight spreads.'),
          MC('A market buy order usually fills at the…', ['Ask','Bid','Last close'], 'Buyers pay the sellers’ asking price.'),
          FILL('A stock that is easy to buy and sell quickly is highly ___.', ['liquid','volatile','leveraged'], 'Liquidity is ease of trading without moving the price.') ]),
    ]},
    {t:'Charts and risk', lessons:[
      L('Reading candlesticks',
        'Each candlestick shows one period’s open, high, low and close (OHLC). The body runs from open to close. Green means it closed higher than it opened, red means lower. The thin wicks mark the high and low.',
        [ MATCH([['Open','First price of the period'],['Close','Last price of the period'],['High','Top of the upper wick'],['Low','Bottom of the lower wick']]),
          TF('A green candle means the close was above the open.', true, 'Green = up for the period.'),
          MC('A candle with a tiny body and long wicks suggests…', ['Buyers and sellers fought to a draw','A huge one-way rally','The market was closed'], 'Price moved a lot but ended near where it started.'),
          FILL('OHLC stands for open, high, low and ___.', ['close','cost','cap'], 'The four prices in every candle.'),
          MC('The thin lines above and below a candle’s body are called…', ['Wicks','Spreads','Tickers'], 'Also called shadows.') ]),
      L('Trends and levels',
        'An uptrend makes higher highs and higher lows. Support is a price where buying has tended to stop declines. Resistance is where selling has capped rallies. A moving average smooths prices to show the trend.',
        [ MC('Higher highs and higher lows describe…', ['An uptrend','A downtrend','A sideways market'], 'Each rally and dip ends higher than the last.'),
          MATCH([['Support','Where declines have stopped'],['Resistance','Where rallies have stalled'],['Moving average','Average over a rolling window'],['Breakout','Price moves past resistance']]),
          TF('Support and resistance levels are guaranteed to hold.', false, 'They are zones where things happened before, not rules.'),
          MC('A 50-day moving average is…', ['The average close of the last 50 days','The price 50 days ago','The highest price in 50 days'], 'It rolls forward each day.'),
          FILL('When price pushes above resistance, it is called a ___.', ['breakout','dividend','split'], 'Breakouts often come with higher volume.') ]),
      L('Managing risk',
        'Professionals decide how much they could lose before they trade. A common rule: risk no more than 1–2% of your account on one trade. Risk/reward compares what you could lose with what you could gain.',
        [ MC('Account: $10,000. Using the 1% rule, the most you would risk on one trade is…', ['$100','$1,000','$10'], '1% of $10,000 = $100.'),
          MC('Stop $2 below entry, target $6 above. The risk/reward is…', ['1:3','3:1','1:6'], 'Risk $2 to make $6.'),
          TF('Doubling your position after a loss to “win it back” is sound risk management.', false, 'That is revenge trading, and it grows losses.'),
          ORDER('Put a disciplined trade in order', ['Pick a setup','Set your stop and target','Size the position','Place the order','Review the result'], 'You need the stop before you can size the trade.'),
          FILL('Choosing how many shares to buy based on your risk is position ___.', ['sizing','trading','margin'], 'Size = amount at risk ÷ distance to stop.') ], '#portfolio'),
    ]},
  ]
},
{
  id:'money', name:'Personal Finance', color:'#C98A12',
  blurb:'Budgeting, emergency funds, credit scores and getting out of debt.',
  units:[
    {t:'Budgeting basics', lessons:[
      L('Where your money goes',
        'A budget is a plan for your income. The 50/30/20 rule is a simple start: 50% to needs, 30% to wants, 20% to savings and paying off debt, all from take-home pay.',
        [ MC('Take-home pay is $3,000 a month. Under 50/30/20, savings get…', ['$600','$900','$1,500'], '20% of $3,000 = $600.'),
          MATCH([['Needs','Rent, groceries, utilities'],['Wants','Streaming, dining out, concerts'],['Savings','Emergency fund, investing'],['Take-home pay','Income after taxes']]),
          TF('A gym membership you rarely use is a need.', false, 'Unused subscriptions are wants, and easy cuts.'),
          FILL('Under 50/30/20, ___% of take-home pay goes to needs.', ['50','30','20'], 'Needs get half.'),
          MC('The first step in making a budget is…', ['Tracking what you actually spend','Cutting all fun spending','Opening a credit card'], 'You can’t plan what you haven’t measured.') ]),
      L('Emergency fund',
        'An emergency fund covers surprises like a job loss or a car repair. Aim for 3–6 months of essential expenses in a safe, easy-to-reach account such as a high-yield savings account.',
        [ MC('Essential costs are $2,000 a month. A 3–6 month emergency fund is…', ['$6,000–$12,000','$2,000','$24,000–$48,000'], '3 × $2,000 to 6 × $2,000.'),
          TF('Emergency funds are best kept in individual stocks.', false, 'Stocks can fall right when you need the cash.'),
          MC('Which is a true emergency?', ['A surprise medical bill','A concert ticket sale','A new phone release'], 'Emergencies are unplanned and necessary.'),
          FILL('Emergency money should be safe and easy to ___.', ['access','forget','invest'], 'You may need it tomorrow.'),
          MC('Why build an emergency fund before investing heavily?', ['So you don’t sell investments at a bad time','Savings always earn more than stocks','Investing is illegal without one'], 'Cash on hand keeps your investments untouched.') ]),
      L('Pay yourself first',
        'Paying yourself first means moving savings out automatically on payday, before you spend. Small automatic amounts add up, and money you never see is money you don’t miss.',
        [ TF('Automating savings on payday makes saving easier.', true, 'It removes the decision each month.'),
          MC('Saving $5 a day for a year adds up to about…', ['$1,825','$365','$500'], '$5 × 365 = $1,825.'),
          ORDER('Order a simple money plan', ['Build a starter emergency fund','Pay off high-interest debt','Grow the fund to 3–6 months','Invest for the long term'], 'Protect yourself, kill expensive debt, then grow.'),
          FILL('Saving before you spend is called paying yourself ___.', ['first','last','back'], 'Savings come out before spending.'),
          MC('Lifestyle creep means…', ['Spending rises as income rises','Prices fall over time','Saving becomes automatic'], 'Raises vanish into new spending.') ], '#tools'),
    ]},
    {t:'Credit and debt', lessons:[
      L('Interest and APR',
        'Interest is the cost of borrowing. APR (annual percentage rate) shows the yearly cost, including many fees. Credit card APRs are often above 20%, so unpaid balances grow quickly.',
        [ MC('A $1,000 card balance at 24% APR sits unpaid for a year. Interest is roughly…', ['$240','$24','$2,400'], '24% of $1,000 ≈ $240, and more once interest compounds.'),
          TF('Paying only the minimum is the cheapest way to clear a credit card.', false, 'Minimums keep most of the balance growing at full APR.'),
          FILL('The yearly cost of borrowing, shown as a percentage, is the ___.', ['APR','ETF','IPO'], 'Annual percentage rate.'),
          MATCH([['Principal','Amount you borrowed'],['Interest','Cost of borrowing'],['APR','Yearly cost as a %'],['Minimum payment','Smallest amount due monthly']]),
          MC('Which usually has the highest interest rate?', ['Credit card','Mortgage','Federal student loan'], 'Unsecured card debt is the priciest.') ]),
      L('Credit scores',
        'A credit score estimates how likely you are to repay. The biggest factors are paying on time and how much of your credit limit you use, called utilization. Keeping utilization under about 30% helps.',
        [ MC('Which matters most for a credit score?', ['Paying bills on time','Your salary','How many bank accounts you have'], 'Payment history is the largest factor.'),
          MC('Limit $5,000, balance $1,000. Utilization is…', ['20%','5%','50%'], '$1,000 ÷ $5,000 = 20%.'),
          TF('Checking your own credit score lowers it.', false, 'Checking your own score is a soft inquiry.'),
          FILL('Using a small share of your credit limit keeps ___ low.', ['utilization','income','APR'], 'Lower utilization looks less risky.'),
          MC('A good credit score can get you…', ['Lower interest rates on loans','Free stocks','Higher taxes'], 'Lenders charge less to reliable borrowers.') ]),
      L('Paying off debt',
        'There are two popular payoff methods. Avalanche: pay extra on the highest-interest debt first, which saves the most money. Snowball: pay off the smallest balance first, for quick wins that keep you going. Either way, pay the minimum on everything.',
        [ MATCH([['Avalanche','Highest interest rate first'],['Snowball','Smallest balance first'],['Minimum payment','Pay on every debt monthly'],['Refinancing','Swap a loan for a cheaper one']]),
          MC('Which method saves the most interest?', ['Avalanche','Snowball','Paying at random'], 'Killing the highest rate first cuts total interest.'),
          TF('With the snowball method you stop paying minimums on bigger debts.', false, 'Always pay every minimum to avoid fees and credit damage.'),
          MC('Debts: card 25% APR, car 6%, student 4%. Avalanche targets first…', ['The card','The car loan','The student loan'], 'Highest rate first.'),
          FILL('Paying the smallest balance first is the debt ___ method.', ['snowball','avalanche','ladder'], 'Small wins build momentum.') ]),
    ]},
  ]
},
{
  id:'biz', name:'Marketing & Business', color:'#C94F78',
  blurb:'Finding customers, standing out, and the numbers that run a business.',
  units:[
    {t:'Marketing basics', lessons:[
      L('The 4 Ps',
        'The marketing mix is often called the 4 Ps: Product (what you sell), Price (what it costs), Place (where people buy it) and Promotion (how people hear about it).',
        [ MATCH([['Product','What you sell'],['Price','What customers pay'],['Place','Where customers buy it'],['Promotion','How customers hear about it']]),
          MC('A brand runs Instagram ads. Which P is that?', ['Promotion','Place','Product'], 'Ads spread the word.'),
          MC('Selling in grocery stores instead of only online changes the…', ['Place','Price','Product'], 'Place is where the sale happens.'),
          TF('Offering a student discount is a Price decision.', true, 'Discounts change what customers pay.'),
          FILL('The 4 Ps are product, price, place and ___.', ['promotion','profit','people'], 'Promotion completes the mix.') ]),
      L('Knowing your customer',
        'Segmentation splits a market into groups with shared needs, by age, location, behavior or values. Your target market is the segment you choose to serve. A persona is a sketch of one typical customer.',
        [ MC('Selling running shoes to marathon runners is choosing a…', ['Target market','Supply chain','Price floor'], 'You picked a segment to serve.'),
          MATCH([['Segmentation','Splitting a market into groups'],['Target market','The group you choose to serve'],['Persona','Profile of a typical customer'],['Demographics','Age, income, location']]),
          TF('Marketing to everyone usually works better than choosing a target.', false, 'A message for everyone speaks to no one.'),
          FILL('Grouping customers by shared traits is called ___.', ['segmentation','distribution','inflation'], 'Segments make messages sharper.'),
          MC('Which is a behavioral segment?', ['People who buy coffee daily','People aged 25–34','People in Chicago'], 'Behavior is what people do, not who or where they are.') ]),
      L('Standing out',
        'A value proposition says why a customer should pick you: the problem you solve and what makes you different. Positioning is the place you want to hold in customers’ minds compared with competitors.',
        [ MC('Which is the strongest value proposition?', ['Groceries at your door in 15 minutes','We are a great company','Quality products for everyone'], 'Specific, customer-focused and different.'),
          TF('Positioning is about how customers see you compared with competitors.', true, 'It is relative by nature.'),
          FILL('The promise of why customers should choose you is your value ___.', ['proposition','chain','ratio'], 'Value proposition.'),
          MC('A brand known as “the safest car” in people’s minds has strong…', ['Positioning','Liquidity','Leverage'], 'It owns one clear idea.'),
          ORDER('Order a basic marketing plan', ['Research the market','Choose a target segment','Write the value proposition','Launch promotion','Measure results'], 'Know who, say why, then spread the word and measure.') ]),
    ]},
    {t:'Business by the numbers', lessons:[
      L('Revenue, profit and margin',
        'Revenue is money from sales. Profit is what is left after costs. Profit margin = profit ÷ revenue. A 20% margin means 20 cents of profit on every dollar of sales.',
        [ MC('Revenue $200,000, costs $150,000. Profit is…', ['$50,000','$350,000','$150,000'], '$200,000 − $150,000.'),
          MC('Profit $50,000 on revenue $200,000. The margin is…', ['25%','50%','4%'], '$50,000 ÷ $200,000 = 25%.'),
          TF('A company with high revenue is always profitable.', false, 'Costs can exceed revenue.'),
          MATCH([['Revenue','Money in from sales'],['Costs','Money spent running the business'],['Profit','Revenue minus costs'],['Margin','Profit as a % of revenue']]),
          FILL('Profit divided by revenue is profit ___.', ['margin','volume','yield'], 'Profit margin.') ]),
      L('Customer economics',
        'CAC (customer acquisition cost) is what you spend to win one customer. LTV (lifetime value) is the profit a customer brings over time. Healthy businesses aim for LTV of about 3× CAC or more.',
        [ MC('$10,000 on ads brings 200 customers. CAC is…', ['$50','$200','$2,000'], '$10,000 ÷ 200.'),
          TF('If LTV is lower than CAC, you lose money on each customer.', true, 'You pay more to win them than they bring in.'),
          MATCH([['CAC','Cost to win one customer'],['LTV','Profit from a customer over time'],['Churn','Customers who leave'],['Retention','Customers who stay']]),
          MC('Which improves LTV?', ['Customers stay subscribed longer','Spending more on ads','Raising CAC'], 'Longer relationships mean more profit per customer.'),
          FILL('The share of customers who cancel is called ___.', ['churn','margin','reach'], 'Lower churn, higher LTV.') ]),
      L('The sales funnel',
        'A funnel tracks people from first hearing about you to buying: awareness, interest, decision, action. Conversion rate = buyers ÷ visitors. Small improvements at each step multiply.',
        [ ORDER('Put the funnel stages in order', ['Awareness','Interest','Decision','Action'], 'AIDA, from first contact to purchase.'),
          MC('1,000 visitors and 30 buy. The conversion rate is…', ['3%','30%','0.3%'], '30 ÷ 1,000.'),
          TF('Doubling your conversion rate can double sales without more traffic.', true, 'Same visitors, twice the buyers.'),
          FILL('Buyers divided by visitors is the ___ rate.', ['conversion','churn','interest'], 'Conversion rate.'),
          MC('Many people add to cart but don’t buy. Which stage leaks?', ['Action (checkout)','Awareness','Interest'], 'They decided but didn’t complete the purchase.') ]),
    ]},
  ]
},
{
  id:'supply', name:'Global Supply Chains', color:'#17929F',
  blurb:'How goods cross the world, who pays for shipping, and how companies handle shocks.',
  units:[
    {t:'How goods get to you', lessons:[
      L('The chain',
        'A supply chain is every step that turns raw materials into a product in your hands: suppliers, manufacturers, distributors, retailers and customers. A phone can pass through a dozen countries before you buy it.',
        [ ORDER('Put the supply chain in order', ['Raw materials','Manufacturer','Distributor','Retailer','Customer'], 'Materials become products that flow toward buyers.'),
          MC('A company that makes finished goods from parts is a…', ['Manufacturer','Retailer','Distributor'], 'Manufacturers transform inputs.'),
          TF('Most complex products rely on suppliers in more than one country.', true, 'Chips, screens and batteries often come from different places.'),
          MATCH([['Supplier','Provides raw materials or parts'],['Manufacturer','Turns inputs into products'],['Distributor','Moves and stores goods in bulk'],['Retailer','Sells to end customers']]),
          FILL('The network that brings a product from raw materials to you is the supply ___.', ['chain','curve','line'], 'Supply chain.') ]),
      L('Moving freight',
        'Most world trade by volume moves by sea in standard containers, counted in TEU (twenty-foot equivalent units). Air is fastest but most expensive. Rail and trucks connect ports to warehouses.',
        [ MC('Which mode carries most world trade by volume?', ['Ocean shipping','Air freight','Trucks'], 'Roughly 80% of goods by volume travel by sea.'),
          MC('A 40-foot container equals how many TEU?', ['2','1','4'], 'TEU = twenty-foot equivalent, so 40 ft = 2.'),
          TF('Air freight is usually the cheapest way to ship heavy goods.', false, 'Air costs many times more per kilogram than ocean.'),
          MATCH([['Ocean','Cheapest per unit in bulk'],['Air','Fastest and most expensive'],['Rail','Long overland bulk hauls'],['Truck','Door-to-door last leg']]),
          FILL('Container capacity is measured in ___.', ['TEU','APR','ETF'], 'Twenty-foot equivalent units.') ], '#SLTW'),
      L('Who pays for what: Incoterms',
        'Incoterms are standard trade terms that say who pays for shipping and who carries the risk. EXW: the buyer handles almost everything from the seller’s door. FOB: risk passes once goods are loaded on the ship. DDP: the seller delivers to the buyer with duties paid.',
        [ MATCH([['EXW','Buyer collects at seller’s site'],['FOB','Risk passes when loaded on ship'],['DDP','Seller delivers, duties paid'],['CIF','Seller pays cost, insurance, freight']]),
          MC('Which term puts the most work on the seller?', ['DDP','EXW','FOB'], 'Delivered Duty Paid: the seller handles it all.'),
          TF('Under FOB, risk passes to the buyer once the goods are loaded on the ship.', true, 'Free On Board.'),
          MC('Incoterms mainly define…', ['Who pays costs and bears risk at each step','Product prices','Import tax rates'], 'They split responsibilities, not prices.'),
          FILL('Standard international trade terms are called ___.', ['Incoterms','tariffs','TEU'], 'Published by the International Chamber of Commerce.') ]),
    ]},
    {t:'Risk and strategy', lessons:[
      L('Just-in-time vs. just-in-case',
        'Just-in-time (JIT) keeps little inventory and gets parts right when they’re needed. It is cheap but fragile. Just-in-case holds extra safety stock. It costs more but survives shocks like the 2021 chip shortage.',
        [ MC('Which strategy keeps minimal inventory?', ['Just-in-time','Just-in-case','Stockpiling'], 'Parts arrive as they’re needed.'),
          TF('Just-in-time supply chains are more exposed to sudden disruptions.', true, 'There’s no buffer when a shipment is late.'),
          FILL('Extra inventory held for surprises is called safety ___.', ['stock','net','margin'], 'Safety stock.'),
          MATCH([['Just-in-time','Parts arrive when needed'],['Just-in-case','Hold extra to absorb shocks'],['Safety stock','Buffer inventory'],['Lead time','Time from order to delivery']]),
          MC('A supplier’s lead time grows from 4 to 10 weeks. What should you do?', ['Order earlier or hold more stock','Cut safety stock','Nothing, it doesn’t matter'], 'Longer lead times need earlier orders or bigger buffers.') ]),
      L('The bullwhip effect',
        'Small changes in customer demand grow bigger at each step up the chain, as retailers, distributors and factories each over-order to be safe. Sharing real sales data up the chain reduces the whipsaw.',
        [ MC('Shoppers buy 5% more. The factory sees orders jump 40%. This is…', ['The bullwhip effect','Inflation','A trade deficit'], 'Each stage amplifies the signal.'),
          TF('Sharing real-time sales data with suppliers can reduce the bullwhip effect.', true, 'Everyone plans from the same real demand.'),
          FILL('Demand swings that grow larger up the chain are the ___ effect.', ['bullwhip','network','halo'], 'Like cracking a whip.'),
          MC('Which makes the bullwhip effect worse?', ['Each stage ordering extra “just to be safe”','Stable, shared forecasts','Smaller, more frequent orders'], 'Padding orders at every stage compounds.'),
          ORDER('Order from smallest to largest demand swings', ['Customer','Retailer','Distributor','Manufacturer'], 'Swings grow as you move away from the customer.') ]),
      L('Trade, tariffs and sourcing',
        'A tariff is a tax on imports. Customs classifies goods with HS codes to set the duty. Companies reduce risk by buying from several countries or by moving production closer to their customers, which is called nearshoring.',
        [ MATCH([['Tariff','Tax on imported goods'],['HS code','Customs product classification'],['Nearshoring','Producing closer to customers'],['Dual sourcing','Two suppliers for one part']]),
          MC('A 25% tariff on a $100 import adds…', ['$25','$2.50','$125'], '25% of $100.'),
          TF('Relying on a single supplier in one country is the lowest-risk setup.', false, 'One disruption can stop everything.'),
          MC('A US company moves a factory from Asia to Mexico. That is…', ['Nearshoring','Offshoring','Vertical integration'], 'Closer to its home market.'),
          FILL('Customs uses ___ codes to classify products.', ['HS','TEU','SKU'], 'Harmonized System codes.') ]),
    ]},
  ]
},
];
})();
